[APPS-510] Offline video MediaRecorder class
blinemedical/react-native-webrtc pull request #2
Opened 2023-11-21 00:40 UTC by katelyn-gallagher

[APPS-510](https://blinemedical.atlassian.net/browse/APPS-510)

## Overview
- Implement typescript class for MediaRecorder
- Functions don't need to do anything yet

## Changes
- Created class, and included a bunch of research on codecs/mime-types in a comment
- Created constructor and functions requested in the ticket, but they don't do anything yet
- Setup sym-links, but still need to test with SCMR to see if they're fully working

## Testing
- Nothing to test yet

2023-11-21 15:18 UTC, Gandri requested changes
Super small feedback nothing crazy :)

2023-11-21 15:25 UTC, katelyn-gallagher commented on .vscode/settings.json
Lol no, I did not. Oops :)

2023-11-22 16:36 UTC, Gandri commented on src/MediaRecorder.ts
> +    };
Per our discussion yesterday, we should follow the conventions of the library for this. Which will involve additional effort. We can for sure kick that off to a separate ticket though! :)  If that's the case let's remove this for now and add a comment to the class saying we will implement this event later

2023-11-28 15:58 UTC, Gandri approved these changes
Looks much better. Yeah I think locking things down for now is fine, if we wanted we could expose mimeType as a constructor arg so we could override it but likely we can easily change that later when we are ready to experiment more

2023-11-28 15:59 UTC, merged